import type { Product } from "@/types/product"

export const products: Product[] = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones. Features active noise cancellation, 30-hour battery life, and comfortable over-ear design.",
    price: 299.99,
    discount: 15,
    discountedPrice: 254.99,
    image: "/sleek-black-headphones.png",
    category: "Audio",
    brand: "SoundMaster",
    model: "WH-1000X",
    rating: 4.8,
    reviews: 245,
    inStock: true,
    inventory: {
      total: 150,
      available: 120,
      reserved: 30,
    },
    weight: 0.25,
    dimensions: "7.5 x 6.5 x 3.5 inches",
    color: "Black",
    warranty: "2 years",
  },
  {
    id: 2,
    name: 'Ultra HD Smart TV 55"',
    description:
      "Transform your living room with this stunning 55-inch Ultra HD Smart TV. Features vibrant colors, sharp contrast, and built-in streaming apps.",
    price: 799.99,
    discount: 10,
    discountedPrice: 719.99,
    image: "/modern-living-room-tv.png",
    category: "TVs",
    brand: "VisionPlus",
    model: "VP-55UHD",
    rating: 4.6,
    reviews: 189,
    inStock: true,
    inventory: {
      total: 75,
      available: 62,
      reserved: 13,
    },
    weight: 15.8,
    dimensions: "48.5 x 28.2 x 3.0 inches",
    color: "Black",
    warranty: "3 years",
  },
  {
    id: 3,
    name: "Professional DSLR Camera",
    description:
      "Capture stunning photos and videos with this professional-grade DSLR camera. Includes 24.2MP sensor, 4K video recording, and advanced autofocus system.",
    price: 1299.99,
    discount: 12, // Add a discount
    discountedPrice: 1143.99, // Calculate the discounted price
    image: "/professional-black-dslr.png",
    category: "Cameras",
    brand: "PhotoPro",
    model: "D850",
    rating: 4.9,
    reviews: 132,
    inStock: true,
    inventory: {
      total: 50,
      available: 42,
      reserved: 8,
    },
    weight: 0.9,
    dimensions: "5.8 x 4.9 x 3.1 inches",
    color: "Black",
    warranty: "1 year",
  },
  {
    id: 4,
    name: 'Gaming Laptop 15.6"',
    description:
      "Dominate your games with this powerful gaming laptop. Features high-performance CPU, dedicated graphics card, and high-refresh-rate display.",
    price: 1499.99,
    discount: 5,
    discountedPrice: 1424.99,
    image: "/rgb-gaming-laptop.png",
    category: "Laptops",
    brand: "GameForce",
    model: "GF-15",
    rating: 4.7,
    reviews: 208,
    inStock: true,
    inventory: {
      total: 100,
      available: 87,
      reserved: 13,
    },
    weight: 2.3,
    dimensions: "14.2 x 10.8 x 0.9 inches",
    color: "Black/RGB",
    warranty: "2 years",
  },
  {
    id: 5,
    name: "Wireless Earbuds with Charging Case",
    description:
      "Experience true wireless freedom with these premium earbuds. Features active noise cancellation, water resistance, and long battery life.",
    price: 149.99,
    discount: 20,
    discountedPrice: 119.99,
    image: "/sleek-wireless-audio.png",
    category: "Audio",
    brand: "SoundMaster",
    model: "AirPods Pro",
    rating: 4.5,
    reviews: 312,
    inStock: true,
    inventory: {
      total: 200,
      available: 156,
      reserved: 44,
    },
    weight: 0.05,
    dimensions: "1.8 x 0.7 x 0.8 inches",
    color: "White",
    warranty: "1 year",
  },
  {
    id: 6,
    name: "Smart Watch with Health Monitoring",
    description:
      "Track your fitness and stay connected with this advanced smartwatch. Features heart rate monitoring, GPS, and customizable watch faces.",
    price: 249.99,
    discount: 20, // Add a discount
    discountedPrice: 199.99, // Calculate the discounted price
    image: "/wrist-worn-wellness.png",
    category: "Wearables",
    brand: "FitTech",
    model: "FT-Watch Pro",
    rating: 4.4,
    reviews: 178,
    inStock: true,
    inventory: {
      total: 120,
      available: 98,
      reserved: 22,
    },
    weight: 0.04,
    dimensions: "1.6 x 1.6 x 0.5 inches",
    color: "Black",
    warranty: "1 year",
  },
  {
    id: 7,
    name: "4K Action Camera",
    description:
      "Capture your adventures in stunning 4K with this rugged action camera. Features waterproof design, image stabilization, and wide-angle lens.",
    price: 199.99,
    discount: 15,
    discountedPrice: 169.99,
    image: "/underwater-adventure.png",
    category: "Cameras",
    brand: "ActionPro",
    model: "AP-4K",
    rating: 4.3,
    reviews: 156,
    inStock: true,
    inventory: {
      total: 80,
      available: 65,
      reserved: 15,
    },
    weight: 0.12,
    dimensions: "2.4 x 1.6 x 1.2 inches",
    color: "Black",
    warranty: "1 year",
  },
  {
    id: 8,
    name: "Portable Bluetooth Speaker",
    description:
      "Take your music anywhere with this portable Bluetooth speaker. Features powerful sound, waterproof design, and 20-hour battery life.",
    price: 89.99,
    discount: 10,
    discountedPrice: 80.99,
    image: "/poolside-beats.png",
    category: "Audio",
    brand: "SoundMaster",
    model: "Boom 3",
    rating: 4.6,
    reviews: 223,
    inStock: true,
    inventory: {
      total: 150,
      available: 132,
      reserved: 18,
    },
    weight: 0.64,
    dimensions: "7.2 x 2.9 x 2.9 inches",
    color: "Blue",
    warranty: "1 year",
  },
  {
    id: 9,
    name: "Ultra-Thin Smartphone",
    description:
      "Experience cutting-edge technology with this ultra-thin smartphone. Features high-resolution display, powerful camera system, and all-day battery life.",
    price: 999.99,
    discount: 5,
    discountedPrice: 949.99,
    image: "/sleek-slate.png",
    category: "Smartphones",
    brand: "TechX",
    model: "X14 Pro",
    rating: 4.7,
    reviews: 342,
    inStock: true,
    inventory: {
      total: 200,
      available: 167,
      reserved: 33,
    },
    weight: 0.17,
    dimensions: "5.8 x 2.8 x 0.3 inches",
    color: "Midnight Blue",
    warranty: "1 year",
  },
  {
    id: 10,
    name: "Smart Home Hub",
    description:
      "Control your entire smart home with this central hub. Compatible with major smart home devices and features voice control.",
    price: 129.99,
    discount: 15, // Add a discount
    discountedPrice: 110.49, // Calculate the discounted price
    image: "/connected-living-hub.png",
    category: "Smart Home",
    brand: "HomeConnect",
    model: "HC-Hub",
    rating: 4.5,
    reviews: 187,
    inStock: true,
    inventory: {
      total: 100,
      available: 82,
      reserved: 18,
    },
    weight: 0.34,
    dimensions: "3.9 x 3.9 x 1.4 inches",
    color: "White",
    warranty: "2 years",
  },
  {
    id: 11,
    name: "Wireless Gaming Mouse",
    description:
      "Gain a competitive edge with this high-performance wireless gaming mouse. Features customizable RGB lighting, programmable buttons, and precise tracking.",
    price: 79.99,
    discount: 0,
    discountedPrice: 79.99,
    image: "/rgb-wireless-gaming-mouse.png",
    category: "Gaming",
    brand: "GameForce",
    model: "GF-Mouse Pro",
    rating: 4.6,
    reviews: 214,
    inStock: true,
    inventory: {
      total: 120,
      available: 103,
      reserved: 17,
    },
    weight: 0.09,
    dimensions: "5.0 x 2.8 x 1.7 inches",
    color: "Black/RGB",
    warranty: "2 years",
  },
  {
    id: 12,
    name: "Mechanical Gaming Keyboard",
    description:
      "Enhance your gaming experience with this mechanical keyboard. Features customizable RGB lighting, programmable macros, and durable construction.",
    price: 129.99,
    discount: 25, // Increase the discount
    discountedPrice: 97.49, // Calculate the discounted price
    image: "/rgb-mechanical-keyboard.png",
    category: "Gaming",
    brand: "GameForce",
    model: "GF-KB Pro",
    rating: 4.7,
    reviews: 198,
    inStock: true,
    inventory: {
      total: 90,
      available: 76,
      reserved: 14,
    },
    weight: 1.2,
    dimensions: "17.3 x 5.2 x 1.4 inches",
    color: "Black/RGB",
    warranty: "2 years",
  },
]
